name: Auto Create PR from main to feature branch

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check if main has new commits not in feature branch
        id: check_commits
        run: |
          git fetch origin main
          if git log origin/main --not origin/${{ env.BRANCH_NAME }} --oneline | grep .; then
            echo "HAS_NEW_COMMITS=true" >> $GITHUB_ENV
          else
            echo "HAS_NEW_COMMITS=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.HAS_NEW_COMMITS == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const baseBranch = '${{ env.BRANCH_NAME }}';
            const headBranch = 'main';
            const title = `Merge main into ${baseBranch}`;
            const body = 'This PR is automatically created to merge latest changes from main into feature branch.';

            // Check if PR already exists
            const existingPrs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${headBranch}`,
              base: baseBranch,
              state: 'open'
            });

            if (existingPrs.data.length === 0) {
              // Create new PR
              await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                head: headBranch,
                base: baseBranch
              });
              console.log(`Created PR: ${title}`);
            } else {
              console.log(`PR already exists: ${existingPrs.data[0].html_url}`);
            }